# -*- coding: utf-8 -*-
"""musteri_segmentasyonu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEaV-tZj0A8sr4Igqdr8ZPilx8puuPXb

# Müşteri Segmentasyonu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import dendrogram, linkage

data = pd.read_csv("customer_segmentation_clustered.csv")

data.head(20)

# Eksi(-) değerlerden kurtulmak İçin :
X = data.values
X[:,0] = np.abs(2*min(X[:,0])) + X[:,0]

X[:,1] = np.abs(2*min(X[:,1])) + X[:,1]
data

"""#### Veri Noktalarını Görselleştir"""

plt.figure(figsize=(10, 8))
plt.scatter(X[:,0],X[:,1], edgecolors="k", alpha=0.7, s=50)
plt.title("Musteri Segmentasyonu Verisi")
plt.xlabel("Gelir(Income)")
plt.ylabel("Harcama Skoru(Spending Score)")
plt.show()

"""### Clustering Modeli Oluşturmak -> Unsupervised Learning"""

kmeans = KMeans(n_clusters=5)
kmeans.fit(X)
cluster_labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_

cluster_centers

"""#### Sonuçları Görselleştirme"""

plt.figure(figsize=(10, 8))
plt.scatter(X[:,0],X[:,1], c=cluster_labels, cmap="viridis", marker="o", edgecolors="k", s=50, alpha=0.7)
plt.scatter(cluster_centers[:,0], cluster_centers[:,1], c="red", s=200, marker="X")
plt.title("K-Means Musteri Segmentasyonu Verisi")
plt.xlabel("Gelir(Income)")
plt.ylabel("Harcama Skoru(Spending Score)")
plt.show()

"""### Görselleştirme"""

linkage_matrix = linkage(X, method="ward")

plt.figure()
dendrogram(linkage_matrix)
plt.title("Dendogram")
plt.xlabel("Veri Noktalari (Her bir musteri)")
plt.ylabel("Uzaklik")

plt.tight_layout()
plt.show()